version: '3.9'

services:
  webserver:
    container_name: nginx
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on: 
      - backend_1
      - backend_2
        
  backend_1:
    container_name: flask_1
    build:
      context: flask
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - database

  backend_2:
    container_name: flask_2
    build:
      context: flask
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5001:5000"
    depends_on:
      - database

  database:
    image: mongo:5.0
    restart: unless-stopped
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=vdt2023
    volumes:
      - database:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | data_tier data_tier:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  database:
