name: Run Unit Test

on:
  pull_request:
    branches:
      - main

  push:
    branches:
     - midterm

jobs:
  test:
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: crudapptest
          MYSQL_USER: demo
          MYSQL_PASSWORD: demo
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    name: Run Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r "10. GK/NguyenTuanAnh/source_code/flask/requirements.txt"

      - uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: "10. GK/NguyenTuanAnh/source_code/flask"
          use-pylint: false
          use-pycodestyle: false
          use-flake8: true
          use-black: false
          use-mypy: false
          use-isort: false
          extra-flake8-options: "--exit-zero --max-line-length=127"

      - name: Run unit test
        run: |
          cd "10. GK/NguyenTuanAnh/source_code/flask"
          python3 -m unittest test.py


      - name: Create Coverage
        if: ${{ github.event_name == 'pull_request' }}
        uses: orgoro/coverage@v3
        with:
            coverageFile: coverage.xml
            token: ${{ secrets.TOKEN_GITHUB }}
