name: Run Unit Test

on:
  pull_request:
    branches:
      - main
      - midterm

  push:
    branches:
     - midterm

jobs:
  test:
    name: Run Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install -r '10. GK/NguyenTuanAnh/source_code/app/requirements.txt'

      - uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: "./source_code/app"
          use-pylint: false
          use-pycodestyle: false
          use-flake8: true
          use-black: false
          use-mypy: false
          use-isort: false
          extra-flake8-options: "--exit-zero --max-line-length=127"

      - name: Run unit test
        run: |
          cd ./source_code/flask
          export MYSQL_HOST={{ secrets.MYSQL_HOST }}
          export MYSQL_USER={{ secrets.MYSQL_USER }}
          export MYSQL_PASSWORD={{ secrets.MYSQL_PASSWORD }}
          export MYSQL_DB={{ secrets.MYSQL_DB_TEST }}
          python3 -m unittest test.py


      - name: Create Coverage
        if: ${{ github.event_name == 'pull_request' }}
        uses: orgoro/coverage@v3
        with:
            coverageFile: coverage.xml
            token: ${{ secrets.TOKEN_GITHUB }}
